cart/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from cart.views import CartView

urlpatterns = patterns('cart.views',
    url(r'^$', CartView.as_view(), name="cart_home"),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wines/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from tastypie.api import Api

from wines.views import WineListView, WineEdit, WineDelete
from wines.api import WineResource

#setup api resources
v1_api = Api(api_name='v1')
v1_api.register(WineResource())


SLUG = '(?P<slug>[\w\d-]+)'

urlpatterns = patterns('wines.views',
                       url(r'^api/', include(v1_api.urls)),
                       url(r'^$', WineListView.as_view(), name="wine_home"),
                       url(r'^' + SLUG + '/$',
                           WineEdit.as_view(), name='wine_edit'),
                       url(r'^' + SLUG + '/delete/$',
                           WineDelete.as_view(), name='wine_delete'),
                       url(r'^page/(?P<page>\d+)/$', WineListView.as_view(
                       ), name='wine_index_paginated')
                       )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workbench/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from tastypie.api import Api
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from workbench.api import WorkFlowResource, BlockResource, RouteResource
from workbench.views import WorkFlowCreate, WorkFlowList, WorkFlowDelete, WorkFlowEdit, BlockEdit

admin.autodiscover()
#setup ajax calls
dajaxice_autodiscover()

#setup api resources
v1_api = Api(api_name='v1')
v1_api.register(WorkFlowResource())
v1_api.register(BlockResource())
v1_api.register(RouteResource())

urlpatterns = patterns('',
                       #default urls here
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^admin_tools/', include('admin_tools.urls')),
                       #url(r'^docs/$', 'docs'),
                       url(r'^about/', TemplateView.as_view(template_name="about.html")),
                       url(r'^account/', include("account.urls")),
                       url(dajaxice_config.dajaxice_url,
                           include('dajaxice.urls')),
                       url(r'^api/', include(v1_api.urls)),
                       #workbench urls
                       url(r'block/(?P<pk>\d+)/$', BlockEdit.as_view(),
                           name='block_edit'),
                       url(r'^$', WorkFlowList.as_view(), name="home"),
                       url(r'^workflow/add/',
                           WorkFlowCreate.as_view(), name="workflow_add"),
                       url(r'^workflow/save/', 'workbench.views.workflow_save',
                           name="workflow_save"),
                       url(
                       r'workflow/(?P<pk>\d+)/delete/$', WorkFlowDelete.as_view(),
                       name='workflow_delete'),
                       url(r'workflow/(?P<pk>\d+)/$', WorkFlowEdit.as_view(),
                           name='workflow_edit'),
                       url(r'^block/create/', 'workbench.views.block_create',
                           name="block_create"),
                       url(r'^results/', include('results.urls')),
                       url(r'^data/', include('datasets.urls')),
                       #restaurant frontend urls
                       url(r'^wines/', include('wines.urls')),
                       url(r'^beers/', include('beers.urls')),
                       url(r'^home/', include('home.urls')),
                       url(r'^cart/', include('cart.urls')),
                       url(r'^orders/', include('orders.urls')),
                       )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

wines/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.core.urlresolvers import reverse
from autoslug import AutoSlugField


class Wine(TimeStampedModel):
    name = models.CharField(max_length=200)
    year = models.SmallIntegerField(max_length=4)
    grapes = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    region = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    onstock = models.PositiveSmallIntegerField(default=1)
    purchased = models.PositiveSmallIntegerField(default=0)
    picture = models.ImageField(upload_to="wines")
    slug = AutoSlugField(populate_from='name',
                         slugify=lambda value: value.replace(' ', '-'))

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        super(Wine, self).save(**kwargs)

    @models.permalink
    def get_absolute_url(self):
        return reverse('wine_edit', kwargs={'pk': self.pk})

# TODO: Defne custom methods here

wines/forms.py
# forms.py
from django.forms import ModelForm
from wines.models import Wine


class WineForm(ModelForm):
    class Meta:
        model = Wine
        exclude = ('purchased',)

wines/views.py
from django.views.generic import ListView, DeleteView, TemplateView
from django.core.urlresolvers import reverse_lazy

from wines.models import Wine


class WineListView(ListView):
    model = Wine
    paginate_by = 6
    allow_empty = True
    template_name = "wines/index.html"


class WineEdit(TemplateView):
    model = Wine
    template_name = "wines/detail.html"

    def get_context_data(self, **kwargs):
        context = super(WineEdit, self).get_context_data(**kwargs)
        context['wine'] = Wine.objects.get(slug=self.kwargs.get('slug', None))
        return context


class WineDelete(DeleteView):
    model = Wine
    success_url = reverse_lazy('wine_index_paginated')

wines/templates/wines/detail.html
{% extends "rbase.html" %}

{% block extra_head %}
    <style type="text/css">
        body {
            padding-top: 50px;
            padding-bottom: 40px;
        }
    </style>
{% endblock %}


{% block body_class %}Wine Details{% endblock %}

{% block body %}
    {% block content %}
        <div class="row-fluid">
            <div id="content" class="span12">
                {% if wine %}
                    <div>

                        <form class="form-horizontal span12">
                            <fieldset>
                                <legend>Wine Details</legend>
                                <br>

                                <div class="row">
                                    <div class="span8">
                                        <div class="control-group">
                                            <label for="name" class="control-label">Name:</label>

                                            <div class="controls">
                                                <input type="text" id="name" name="name" value="{{ wine.name }}">
                                                <span class="help-inline"></span>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="grapes" class="control-label">Grapes:</label>

                                            <div class="controls">
                                                <input type="text" id="grapes" name="grapes" value="{{ wine.grapes }}">
                                                <span class="help-inline"></span>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="country" class="control-label">Country:</label>

                                            <div class="controls">
                                                <input type="text" id="country" name="country"
                                                       value="{{ wine.country }}">
                                                <span class="help-inline"></span>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="region" class="control-label">Region:</label>

                                            <div class="controls">
                                                <input type="text" id="region" name="region" value="{{ wine.region }}">
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="year" class="control-label">Year:</label>

                                            <div class="controls">
                                                <select class="input-small" id="year" name="year"
                                                        value="{{ wine.year }}">
                                                    <option>2012</option>
                                                    <option>2011</option>
                                                    <option>2010</option>
                                                    <option>2009</option>
                                                    <option>2008</option>
                                                    <option>2007</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="description" class="control-label">Notes:</label>

                                            <div class="controls">
                                                <textarea id="description" name="description" style="width: 90%;"
                                                          rows="6">{{ wine.description }}</textarea>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="span4">
                                        <div class="well"
                                             style="width: 180px;text-align: center;width:50%;margin: 0px auto;">
                                            <p><img id="picture" width="180"
                                                    src="../../site_media/media/{{ wine.picture }}"></p>

                                            <p style="color:#999;">To change the picture, drag a new picture from your
                                                file system onto the box above.</p>
                                        </div>
                                    </div>

                                </div>

                            </fieldset>

                            <div class="form-actions">
                               <button type="button" onclick="javascript:;" class="btn btn-primary item_add">Order</button>
                                <a href="javascript: history.go(-1)" class="btn">Back</a>
                            </div>

                        </form>
                    </div>
                {% else %}
                    <p>No data available.</p>
                {% endif %}
            </div>
        </div>
    {% endblock %}
{% endblock %}

wines/templates/wines/index.html
{% extends "rbase.html" %}
{% load static %}
{% load bootstrap_pagination %}

{% block extra_head %}
    <style type="text/css">
        body {
            padding-top: 50px;
            padding-bottom: 40px;
        }
    </style>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/simpleCart.min.js" %}"></script>
<script>
  simpleCart({
    // array representing the format and columns of the cart,
    // see the cart columns documentation
    cartColumns: [
        { attr: "name", label: "Name"},
        { view: "currency", attr: "price", label: "Price"},
        { view: "decrement", label: false},
        { attr: "quantity", label: "Qty"},
        { view: "increment", label: false},
        { view: "currency", attr: "total", label: "SubTotal" },
        { view: "remove", text: "Remove", label: false}
    ],

    // "div" or "table" - builds the cart as a 
    // table or collection of divs
    cartStyle: "table", 

    // how simpleCart should checkout, see the 
    // checkout reference for more info 
    checkout: { 
        type: "PayPal" , 
        email: "you@yours.com" 
    },

    // set the currency, see the currency 
    // reference for more info
    currency: "USD",

    // collection of arbitrary data you may want to store 
    // with the cart, such as customer info
    data: {},

    // set the cart langauge 
    // (may be used for checkout)
    language: "english-us",

    // array of item fields that will not be 
    // sent to checkout
    excludeFromCheckout: [],

    // custom function to add shipping cost
    shippingCustom: null,

    // flat rate shipping option
    shippingFlatRate: 0,

    // added shipping based on this value 
    // multiplied by the cart quantity
    shippingQuantityRate: 0,

    // added shipping based on this value 
    // multiplied by the cart subtotal
    shippingTotalRate: 0,

    // tax rate applied to cart subtotal
    taxRate: 0,

    // true if tax should be applied to shipping
    taxShipping: false,

    // event callbacks 
    beforeAdd           : null,
    afterAdd            : null,
    load                : null,
    beforeSave      : null,
    afterSave           : null,
    update          : null,
    ready           : null,
    checkoutSuccess : null,
    checkoutFail        : null,
    beforeCheckout      : null,
        beforeRemove           : null
});
</script>
{% endblock %}


{% block body_class %}Wines{% endblock %}

{% block body %}
    {% block content %}
        <div class="row">
            <div id="products" class="span10">
                {% if wine_list %}
                        <ul id="catalog" class="thumbnails">
                            {% for wine in wine_list %}
                                <div class="simpleCart_shelfItem">
                                <li id="catalogid" val="{{ wine.slug }}" class="span3">
                                    <a href="{{ wine.slug }}/" class="thumbnail plain" style="text-align: center;">
                                        <img src="{{ MEDIA_URL }}{{ wine.picture }}" height="150" width="125" class="hoverZoomLink item_thumb">
                                        <h5 class="item_name">{{ wine.name }}</h5>
                                        {{ wine.year }} {{ wine.grapes }}<br>
                                        <i class="icon-globe"></i> {{ wine.region }}, {{ wine.country }}
                                    </a>
                                    <span align="center" class="item_price">Price: ${{ wine.price }}</span> 
                                    <span align="center" >QTY: <input style="text-align: right; width: 20px;" type="text" value="1" class="item_Quantity"></span>                              
                                    <button type="button" onclick="javascript:;" class="btn btn-mini btn-primary item_add">Order</button>
                                </li>
                                </div>
                            {% endfor %}
                        </ul>
                            {% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
                {% else %}
                    <p>No wines are available.</p>
                    <a href="javascript: history.go(-1)" class="btn">Back</a>
                {% endif %}            
            </div>
            <div class="span2">{% include "cart.html" %}</div>
        </div>
    {% endblock %}
{% endblock %}